class FinancialPeriodSerializer < ActiveModel::Serializer
  attributes :id, :periodenddate, :fiscalyear, :totalrevenue,
  :grossprofit,
  :researchdevelopmentexpense,
  :ebit,
  :incomebeforetaxes,
  :netincome,
  :cashandcashequivalents,
  :cashcashequivalentsandshortterminvestments,
  :othercurrentassets,
  :inventoriesnet,
  :totalcurrentassets,
  :intangibleassets,
  :propertyplantequipmentnet,
  :goodwill, 
  :otherassets, 
  :totalassets, 
  :othercurrentliabilities, 
  :totalshorttermdebt,
  :totalcurrentliabilities, 
  :otherliabilities, 
  :totallongtermdebt, 
  :totalliabilities, 
  :retainedearnings,
  :totalstockholdersequity, 
  :cashfromoperatingactivities,
  :cashfrominvestingactivities, 
  :cashfromfinancingactivities, 
  :capitalexpenditures,
  :cfdepreciationamortization, 
  :netchangeincash, 
  :formtype, 
  :audited, 
  :original, 
  :amended, 
  :preliminary, 
  :currencycode, 
  :crosscalculated, 
  :usdconversionrate,
  :company_id
 

end
